<?php

namespace Database\Seeders;

use App\Models\Tour;
use App\Models\TourGallery;
use App\Models\TourItinerary;
use Illuminate\Database\Seeder;

class TourSeeder extends Seeder
{
    public function run(): void
    {
        $tours = [
            [
                'id'                => 'b1111111-1111-1111-1111-111111111111',
                'slug'              => 'bali-bliss-7-nights',
                'name'              => 'Bali Bliss',
                'category'          => 'world-travellers',
                'region'            => 'asia',
                'destination'       => 'Bali, Indonesia',
                'duration'          => 7,
                'group_size_min'    => 2,
                'group_size_max'    => 20,
                'price_per_person'  => 65000,
                'hero_image'        => 'https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=800&q=85&auto=format&fit=crop',
                'short_description' => "Explore Ubud's terraced rice fields, ancient temples, and pristine beaches of Seminyak.",
                'description'       => 'Discover the Island of the Gods on this immersive 7-night Bali journey. From the spiritual heart of Ubud to the sun-kissed shores of Seminyak, this tour blends culture, nature, and relaxation in perfect harmony.',
                'seo_description'   => 'Book Bali tour packages from Nagpur with Trendzy Tours. 7 nights in Bali from ₹65,000 per person.',
                'highlights'        => ['Ubud rice terraces', 'Tanah Lot temple sunset', 'Kuta Beach', 'Traditional Kecak dance', 'Spa day'],
                'inclusions'        => ['Return flights from Nagpur', '7 nights 4-star hotel', 'Daily breakfast', 'All transfers', 'Guide'],
                'exclusions'        => ['Visa fees', 'Personal expenses', 'Optional activities'],
                'featured'          => true,
                'published_at'      => '2025-01-10',
                'gallery'           => ['https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=800&q=85&auto=format&fit=crop'],
                'itinerary'         => [
                    ['day' => 1, 'title' => 'Arrival in Bali',  'description' => 'Land in Denpasar, transfer to Seminyak hotel.',                       'meals' => ['Dinner'],                   'accommodation' => 'Seminyak Beach Hotel'],
                    ['day' => 2, 'title' => 'Ubud Cultural Day','description' => 'Visit Ubud Palace, Monkey Forest, and rice terraces.',                 'meals' => ['Breakfast', 'Lunch'],        'accommodation' => null],
                    ['day' => 3, 'title' => 'Temple Trail',     'description' => 'Tanah Lot, Uluwatu temple and Kecak fire dance.',                      'meals' => ['Breakfast'],                 'accommodation' => null],
                    ['day' => 4, 'title' => 'Adventure Day',    'description' => 'White water rafting on Ayung River, cooking class.',                   'meals' => ['Breakfast', 'Lunch'],        'accommodation' => null],
                    ['day' => 5, 'title' => 'Beach & Spa',      'description' => 'Relaxing day at Seminyak beach, traditional Balinese spa.',            'meals' => ['Breakfast'],                 'accommodation' => null],
                    ['day' => 6, 'title' => 'North Bali',       'description' => 'Lovina beach, Gitgit waterfall, Bali Botanical Garden.',               'meals' => ['Breakfast'],                 'accommodation' => null],
                    ['day' => 7, 'title' => 'Departure',        'description' => 'Morning at leisure, transfer to Denpasar airport.',                    'meals' => ['Breakfast'],                 'accommodation' => null],
                ],
            ],
            [
                'id'                => 'b2222222-2222-2222-2222-222222222222',
                'slug'              => 'rajasthan-royal-10-nights',
                'name'              => 'Rajasthan Royal',
                'category'          => 'domestic',
                'region'            => 'asia',
                'destination'       => 'Rajasthan, India',
                'duration'          => 10,
                'group_size_min'    => 2,
                'group_size_max'    => 25,
                'price_per_person'  => 42000,
                'hero_image'        => 'https://images.unsplash.com/photo-1477587458883-47145ed94373?w=800&q=85&auto=format&fit=crop',
                'short_description' => 'Palaces, forts, and the golden desert of the Land of Kings.',
                'description'       => 'Step into a world of maharajas on this royal Rajasthan circuit covering Jaipur, Jodhpur, Jaisalmer, and Udaipur. Experience camel safaris, heritage hotel stays, and vibrant bazaars.',
                'seo_description'   => 'Rajasthan tour packages from Nagpur. 10 nights across Jaipur, Jodhpur, Jaisalmer & Udaipur from ₹42,000.',
                'highlights'        => ['Jaipur Pink City', 'Mehrangarh Fort Jodhpur', 'Jaisalmer desert safari', 'Lake Pichola Udaipur', 'Heritage hotel stay'],
                'inclusions'        => ['Train/bus transfers within Rajasthan', '10 nights heritage hotels', 'Daily breakfast & dinner', 'Guide', 'Camel safari'],
                'exclusions'        => ['Flights to/from Jaipur', 'Personal expenses'],
                'featured'          => true,
                'published_at'      => '2025-01-15',
                'gallery'           => ['https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=800&q=85&auto=format&fit=crop'],
                'itinerary'         => [
                    ['day' => 1,  'title' => 'Arrive Jaipur',          'description' => 'Pink City welcome, Hawa Mahal visit.',                              'meals' => ['Dinner'],              'accommodation' => null],
                    ['day' => 2,  'title' => 'Jaipur Forts',           'description' => 'Amber Fort, City Palace, Jantar Mantar.',                            'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 3,  'title' => 'Jaipur to Jodhpur',      'description' => 'Scenic drive, arrive Jodhpur.',                                      'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 4,  'title' => 'Jodhpur Blue City',      'description' => 'Mehrangarh Fort, Jaswant Thada, clock tower bazaar.',                'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 5,  'title' => 'Jodhpur to Jaisalmer',   'description' => 'Drive through desert landscape.',                                    'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 6,  'title' => 'Jaisalmer Fort & Desert','description' => 'Jaisalmer Fort, Patwon ki Haveli, Sam sand dunes.',                  'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 7,  'title' => 'Desert Safari',          'description' => 'Camel safari sunrise, folk music under the stars.',                  'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 8,  'title' => 'Jaisalmer to Udaipur',   'description' => 'Long scenic drive, arrive City of Lakes.',                           'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 9,  'title' => 'Udaipur Lakes',          'description' => 'Lake Pichola boat ride, City Palace, Saheliyon ki Bari.',            'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 10, 'title' => 'Departure from Udaipur', 'description' => 'Morning at leisure, airport transfer.',                              'meals' => ['Breakfast'],           'accommodation' => null],
                ],
            ],
            [
                'id'                => 'b3333333-3333-3333-3333-333333333333',
                'slug'              => 'europe-grand-tour-14-nights',
                'name'              => 'Europe Grand Tour',
                'category'          => 'world-travellers',
                'region'            => 'europe',
                'destination'       => 'Paris, Rome, Switzerland',
                'duration'          => 14,
                'group_size_min'    => 10,
                'group_size_max'    => 30,
                'price_per_person'  => 185000,
                'hero_image'        => 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=85&auto=format&fit=crop',
                'short_description' => 'Paris romance, Roman history, and Swiss alpine grandeur in one iconic journey.',
                'description'       => "A bucket-list European circuit covering the best of France, Italy, and Switzerland. From the Eiffel Tower to the Colosseum and Jungfraujoch, this tour delivers Europe's greatest hits with Trendzy's signature care.",
                'seo_description'   => 'Europe tour packages from Nagpur. 14 nights in Paris, Rome & Switzerland from ₹1,85,000 per person.',
                'highlights'        => ['Eiffel Tower Paris', 'Colosseum Rome', 'Vatican Museum', 'Jungfraujoch Top of Europe', 'Venice gondola'],
                'inclusions'        => ['Return flights', '14 nights 4-star hotels', 'Daily breakfast', 'Eurocoach travel', 'English-speaking guide'],
                'exclusions'        => ['Visa fees', 'Personal expenses', 'Optional city tours'],
                'featured'          => true,
                'published_at'      => '2025-02-01',
                'gallery'           => ['https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=85&auto=format&fit=crop'],
                'itinerary'         => [
                    ['day' => 1,  'title' => 'Departure from India',   'description' => 'Overnight flight to Paris.',                                          'meals' => [],                      'accommodation' => null],
                    ['day' => 2,  'title' => 'Arrive Paris',           'description' => 'Hotel check-in, Seine River cruise, Eiffel Tower.',                  'meals' => ['Dinner'],              'accommodation' => null],
                    ['day' => 3,  'title' => 'Paris City Tour',        'description' => "Louvre, Champs-Élysées, Arc de Triomphe, Versailles.",                'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 4,  'title' => 'Paris to Switzerland',   'description' => 'Eurocoach to Lucerne, Lake view evening.',                            'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 5,  'title' => 'Jungfraujoch Day',       'description' => 'Train journey to Top of Europe (3,454m).',                            'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 6,  'title' => 'Lucerne & Mt Titlis',    'description' => 'Mt Titlis cable car, Lucerne old town.',                              'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 7,  'title' => 'Switzerland to Italy',   'description' => 'Coach to Milan, optional fashion district.',                          'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 8,  'title' => 'Venice',                 'description' => "Gondola ride, St Mark's Basilica, Rialto Bridge.",                    'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 9,  'title' => 'Florence',               'description' => 'David sculpture, Uffizi Gallery, Ponte Vecchio.',                     'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 10, 'title' => 'Rome Arrival',           'description' => 'Colosseum, Roman Forum, Trevi Fountain.',                             'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 11, 'title' => 'Vatican Day',            'description' => "Vatican Museums, Sistine Chapel, St Peter's Basilica.",               'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 12, 'title' => 'Rome at Leisure',        'description' => 'Shopping, local cuisine exploration.',                                'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 13, 'title' => 'Departure Flight',       'description' => 'Transfer to Rome Fiumicino airport.',                                 'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 14, 'title' => 'Arrive India',           'description' => 'Welcome home.',                                                       'meals' => [],                      'accommodation' => null],
                ],
            ],
            [
                'id'                => 'b4444444-4444-4444-4444-444444444444',
                'slug'              => 'dubai-extravaganza-5-nights',
                'name'              => 'Dubai Extravaganza',
                'category'          => 'world-travellers',
                'region'            => 'asia',
                'destination'       => 'Dubai, UAE',
                'duration'          => 5,
                'group_size_min'    => 2,
                'group_size_max'    => 30,
                'price_per_person'  => 55000,
                'hero_image'        => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=85&auto=format&fit=crop',
                'short_description' => 'Burj Khalifa, desert safaris, and luxury shopping in the city of superlatives.',
                'description'       => 'Experience the dazzle of Dubai — the world\'s tallest building, a thrilling desert safari, and some of the best shopping on the planet. Perfect for families, couples, and friends.',
                'seo_description'   => 'Dubai tour packages from Nagpur. 5 nights in Dubai from ₹55,000 per person with Trendzy Tours.',
                'highlights'        => ['Burj Khalifa observation deck', 'Desert safari with BBQ dinner', 'Dubai Mall & fountain show', 'Dhow cruise', 'Palm Jumeirah'],
                'inclusions'        => ['Return flights', '5 nights 4-star hotel', 'Daily breakfast', 'All sightseeing', 'Desert safari'],
                'exclusions'        => ['Visa fees', 'Personal shopping', 'Optional activities'],
                'featured'          => true,
                'published_at'      => '2025-01-20',
                'gallery'           => ['https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=85&auto=format&fit=crop'],
                'itinerary'         => [
                    ['day' => 1, 'title' => 'Arrive Dubai',      'description' => 'Airport pickup, hotel check-in, Dubai Mall fountain show.',   'meals' => ['Dinner'],              'accommodation' => null],
                    ['day' => 2, 'title' => 'City Tour',         'description' => 'Burj Khalifa, Dubai Frame, Gold Souk, Spice Souk.',           'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 3, 'title' => 'Desert Safari',     'description' => 'Dune bashing, camel ride, BBQ dinner under the stars.',       'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 4, 'title' => 'Modern Dubai',      'description' => 'Palm Jumeirah, Atlantis, Dubai Marina walk.',                 'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 5, 'title' => 'Dhow Cruise & Departure', 'description' => 'Morning dhow cruise, transfer to airport.',            'meals' => ['Breakfast'],           'accommodation' => null],
                ],
            ],
            [
                'id'                => 'b5555555-5555-5555-5555-555555555555',
                'slug'              => 'kerala-backwaters-ladies-only-6-nights',
                'name'              => 'Kerala Backwaters – Ladies Only',
                'category'          => 'ladies-only',
                'region'            => 'asia',
                'destination'       => 'Kerala, India',
                'duration'          => 6,
                'group_size_min'    => 6,
                'group_size_max'    => 20,
                'price_per_person'  => 32000,
                'hero_image'        => 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=85&auto=format&fit=crop',
                'short_description' => "Houseboat serenity, Ayurveda, and the lush green of God's Own Country — for women only.",
                'description'       => "A specially curated ladies-only retreat through Kerala's backwaters, hills, and beaches. All accommodations, guides, and drivers are women-friendly. Enjoy Ayurvedic spa treatments, houseboat stays, and the warmth of Kerala culture in a safe, supportive group.",
                'seo_description'   => 'Ladies only Kerala tour from Nagpur. 6 nights women-exclusive travel with Trendzy Tours from ₹32,000.',
                'highlights'        => ['Alleppey houseboat stay', 'Munnar tea gardens', 'Ayurvedic spa', 'Kathakali performance', 'Kovalam beach'],
                'inclusions'        => ['Train to Kochi + all local travel', '6 nights (incl. houseboat)', 'Daily breakfast & dinner', 'Women guide', 'Spa session'],
                'exclusions'        => ['Train from Nagpur to Kochi', 'Personal expenses'],
                'featured'          => true,
                'published_at'      => '2025-02-10',
                'gallery'           => ['https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=85&auto=format&fit=crop'],
                'itinerary'         => [
                    ['day' => 1, 'title' => 'Arrive Kochi',        'description' => 'Fort Kochi walking tour, Chinese fishing nets, sunset.',                       'meals' => ['Dinner'],                         'accommodation' => null],
                    ['day' => 2, 'title' => 'Munnar Hills',         'description' => 'Tea museum, Top Station viewpoint, tea plantation walk.',                    'meals' => ['Breakfast', 'Dinner'],            'accommodation' => null],
                    ['day' => 3, 'title' => 'Periyar Wildlife',     'description' => 'Boat safari in Periyar Lake, spice garden tour.',                            'meals' => ['Breakfast', 'Dinner'],            'accommodation' => null],
                    ['day' => 4, 'title' => 'Alleppey Houseboat',   'description' => 'Board private houseboat, cruise the backwaters.',                            'meals' => ['Breakfast', 'Lunch', 'Dinner'],   'accommodation' => null],
                    ['day' => 5, 'title' => 'Kovalam Beach',        'description' => 'Ayurvedic full-body massage, beach relaxation.',                             'meals' => ['Breakfast', 'Dinner'],            'accommodation' => null],
                    ['day' => 6, 'title' => 'Departure',            'description' => 'Morning yoga, transfer to Trivandrum airport.',                              'meals' => ['Breakfast'],                      'accommodation' => null],
                ],
            ],
            [
                'id'                => 'b6666666-6666-6666-6666-666666666666',
                'slug'              => 'north-sikkim-adventure-5-nights',
                'name'              => 'North Sikkim Adventure',
                'category'          => 'domestic',
                'region'            => 'asia',
                'destination'       => 'Sikkim, India',
                'duration'          => 5,
                'group_size_min'    => 4,
                'group_size_max'    => 20,
                'price_per_person'  => 28000,
                'hero_image'        => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=85&auto=format&fit=crop',
                'short_description' => 'Himalayan meadows, yak rides, and the pristine Gurudongmar Lake in North Sikkim.',
                'description'       => "A high-altitude adventure through North Sikkim's remote valleys, Buddhist monasteries, and the sacred Gurudongmar Lake at 17,800 feet. Perfect for nature lovers and adventure seekers.",
                'seo_description'   => 'North Sikkim tour packages from Nagpur. 5 nights adventure with Trendzy Tours from ₹28,000 per person.',
                'highlights'        => ['Gurudongmar Lake (17,800 ft)', 'Yak ride at Yumthang', 'Lachen monastery', 'Himalayan panoramas', 'Gangtok MG Marg'],
                'inclusions'        => ['All local transport', '5 nights hotels/guesthouses', 'All meals', 'Permits', 'Local guide'],
                'exclusions'        => ['Flights to/from Bagdogra', 'Personal expenses', 'Tips'],
                'featured'          => false,
                'published_at'      => '2025-02-15',
                'gallery'           => ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=85&auto=format&fit=crop'],
                'itinerary'         => [
                    ['day' => 1, 'title' => 'Bagdogra to Gangtok', 'description' => 'Scenic drive through tea estates, Gangtok evening.',              'meals' => ['Dinner'],              'accommodation' => null],
                    ['day' => 2, 'title' => 'Gangtok to Lachen',   'description' => 'Journey through Teesta valley, Lachen monastery.',               'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 3, 'title' => 'Gurudongmar Lake',    'description' => 'Pre-dawn drive to sacred lake at 17,800 ft.',                    'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 4, 'title' => 'Lachen to Yumthang', 'description' => 'Valley of Flowers, yak rides at Yumthang.',                      'meals' => ['Breakfast', 'Dinner'], 'accommodation' => null],
                    ['day' => 5, 'title' => 'Return to Gangtok',  'description' => 'Rumtek Monastery, MG Marg, departure.',                          'meals' => ['Breakfast'],           'accommodation' => null],
                ],
            ],
            [
                'id'                => 'b7777777-7777-7777-7777-777777777777',
                'slug'              => 'mediterranean-cruise-10-nights',
                'name'              => 'Mediterranean Cruise',
                'category'          => 'cruise',
                'region'            => 'europe',
                'destination'       => 'Mediterranean – Greece, Italy, Croatia',
                'duration'          => 10,
                'group_size_min'    => 2,
                'group_size_max'    => 50,
                'price_per_person'  => 220000,
                'hero_image'        => 'https://images.unsplash.com/photo-1548574505-5e239809ee19?w=800&q=85&auto=format&fit=crop',
                'short_description' => 'Sail the blue Mediterranean visiting Santorini, Rome, Dubrovnik, and Barcelona.',
                'description'       => "A dream cruise through the Mediterranean's most iconic ports. Wake up in a different paradise each morning — from Santorini's white-washed cliffs to the Game of Thrones streets of Dubrovnik.",
                'seo_description'   => 'Mediterranean cruise packages from India. 10 nights cruise tour from ₹2,20,000 per person with Trendzy Tours.',
                'highlights'        => ['Santorini caldera views', 'Dubrovnik old city walls', 'Barcelona La Sagrada Família', 'Amalfi Coast', 'Athens Acropolis'],
                'inclusions'        => ['Return flights to Barcelona', '10-night cruise (inside cabin)', 'All meals on board', 'Port taxes', 'Shore excursions'],
                'exclusions'        => ['Visa fees', 'Drinks packages', 'Gratuities', 'Optional shore tours'],
                'featured'          => true,
                'published_at'      => '2025-03-01',
                'gallery'           => ['https://images.unsplash.com/photo-1548574505-5e239809ee19?w=800&q=85&auto=format&fit=crop'],
                'itinerary'         => [
                    ['day' => 1,  'title' => 'Fly to Barcelona',       'description' => 'Embark cruise ship, welcome dinner.',                                     'meals' => ['Dinner'],                       'accommodation' => null],
                    ['day' => 2,  'title' => 'At Sea',                 'description' => 'Deck activities, spa, evening entertainment.',                            'meals' => ['Breakfast', 'Lunch', 'Dinner'], 'accommodation' => null],
                    ['day' => 3,  'title' => 'Marseille, France',      'description' => 'Old Port, Notre-Dame de la Garde, Calanques.',                            'meals' => ['Breakfast', 'Lunch', 'Dinner'], 'accommodation' => null],
                    ['day' => 4,  'title' => 'Rome (Civitavecchia)',   'description' => 'Optional Vatican or Colosseum excursion.',                                'meals' => ['Breakfast', 'Lunch', 'Dinner'], 'accommodation' => null],
                    ['day' => 5,  'title' => 'Naples / Amalfi',        'description' => 'Pompeii ruins, Amalfi Coast drive.',                                      'meals' => ['Breakfast', 'Lunch', 'Dinner'], 'accommodation' => null],
                    ['day' => 6,  'title' => 'Santorini, Greece',      'description' => 'Oia village, caldera views, black sand beach.',                           'meals' => ['Breakfast', 'Lunch', 'Dinner'], 'accommodation' => null],
                    ['day' => 7,  'title' => 'Athens (Piraeus)',        'description' => 'Acropolis, Parthenon, Plaka neighbourhood.',                              'meals' => ['Breakfast', 'Lunch', 'Dinner'], 'accommodation' => null],
                    ['day' => 8,  'title' => 'Dubrovnik, Croatia',     'description' => 'City walls walk, Game of Thrones locations.',                             'meals' => ['Breakfast', 'Lunch', 'Dinner'], 'accommodation' => null],
                    ['day' => 9,  'title' => 'At Sea',                 'description' => 'Relaxation day, farewell gala dinner.',                                   'meals' => ['Breakfast', 'Lunch', 'Dinner'], 'accommodation' => null],
                    ['day' => 10, 'title' => 'Barcelona – Disembark',  'description' => 'Disembark, city tour option, fly home.',                                  'meals' => ['Breakfast'],                    'accommodation' => null],
                ],
            ],
            [
                'id'                => 'b8888888-8888-8888-8888-888888888888',
                'slug'              => 'thailand-discovery-7-nights',
                'name'              => 'Thailand Discovery',
                'category'          => 'world-travellers',
                'region'            => 'asia',
                'destination'       => 'Bangkok & Phuket, Thailand',
                'duration'          => 7,
                'group_size_min'    => 2,
                'group_size_max'    => 25,
                'price_per_person'  => 58000,
                'hero_image'        => 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=85&auto=format&fit=crop',
                'short_description' => 'Golden temples of Bangkok and the turquoise waters of Phuket.',
                'description'       => 'Discover the best of Thailand — the buzzing street food scene and royal temples of Bangkok, followed by island-hopping and beach bliss in Phuket.',
                'seo_description'   => 'Thailand tour packages from Nagpur. 7 nights Bangkok & Phuket from ₹58,000 per person with Trendzy Tours.',
                'highlights'        => ['Grand Palace Bangkok', 'Phi Phi Islands', 'Elephant sanctuary', 'Floating market', 'Patong Beach'],
                'inclusions'        => ['Return flights', '7 nights hotels', 'Daily breakfast', 'Bangkok-Phuket domestic flight', 'All transfers'],
                'exclusions'        => ['Visa on arrival fees', 'Personal expenses', 'Optional tours'],
                'featured'          => false,
                'published_at'      => '2025-01-25',
                'gallery'           => ['https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=85&auto=format&fit=crop'],
                'itinerary'         => [
                    ['day' => 1, 'title' => 'Arrive Bangkok',      'description' => 'Hotel check-in, Khao San Road evening.',                                 'meals' => ['Dinner'],              'accommodation' => null],
                    ['day' => 2, 'title' => 'Bangkok Temples',     'description' => 'Grand Palace, Wat Pho, Wat Arun, Chao Phraya river.',                    'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 3, 'title' => 'Bangkok Markets',     'description' => 'Damnoen Saduak floating market, Jim Thompson House.',                   'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 4, 'title' => 'Fly to Phuket',       'description' => 'Morning flight, check-in, Patong Beach afternoon.',                     'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 5, 'title' => 'Phi Phi Islands',     'description' => 'Speedboat day trip, snorkelling, Maya Bay.',                            'meals' => ['Breakfast', 'Lunch'],  'accommodation' => null],
                    ['day' => 6, 'title' => 'Elephant Sanctuary',  'description' => 'Ethical elephant experience, Big Buddha, Promthep Cape.',               'meals' => ['Breakfast'],           'accommodation' => null],
                    ['day' => 7, 'title' => 'Departure',           'description' => 'Morning at leisure, transfer to Phuket airport.',                       'meals' => ['Breakfast'],           'accommodation' => null],
                ],
            ],
        ];

        foreach ($tours as $tourData) {
            $gallery   = $tourData['gallery'];
            $itinerary = $tourData['itinerary'];
            unset($tourData['gallery'], $tourData['itinerary']);

            $tour = Tour::create($tourData);

            foreach ($gallery as $position => $imageUrl) {
                TourGallery::create([
                    'tour_id'   => $tour->id,
                    'image_url' => $imageUrl,
                    'position'  => $position,
                ]);
            }

            foreach ($itinerary as $day) {
                TourItinerary::create([
                    'tour_id'       => $tour->id,
                    'day'           => $day['day'],
                    'title'         => $day['title'],
                    'description'   => $day['description'],
                    'meals'         => $day['meals'],
                    'accommodation' => $day['accommodation'],
                ]);
            }
        }
    }
}
